baseURL = "https://master.d2fvrafk9v089j.amplifyapp.com/"
languageCode = "en-us"
title = "AWS Neuropointillist Workshops"
theme = "hugo-learn-hpc"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
googleAnalytics = "UA-100198268-2"


[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = true
description = "AWS Neuropointillist Workshops"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle = false


[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]


[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false


[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> AWS - Research"
url = "https://aws.amazon.com/government-education/research-and-technical-computing"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-users'></i> Authors"
url = "https://https://master.dh0bc6a3ml9m0.amplifyapp.com//authors.html"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Feedback"
url = "https://survey.immersionday.com/xPnUMpDGg"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Stay in Touch"
url="https://pages.awscloud.com/GLOBAL-public-OE-Flux-2020-reg-event.html"
weight = 40

